##Configurations for training the quntum kernel alignment 

ray_config:
  ray_local_mode:         False
  num_cpus:               30
  num_gpus:               2
  method:                 QuantumKernels
  ray_logging_path:       logs/checkerboard
  ray_num_trial_samples:  5
  type:                   train

## DataSet Configuration
dataset:
  name:              fashion_mnist
  file:              /Users/digvijaysinhajarekar/Developer/fakeart/data/fashion_mnist_2.npy
  training_size:     0.50
  testing_size:      0.50
  validation_size:   0.0

## Quantum Kernel Model Configuration
qkernel:
  device:           lightning.qubit
  n_qubits:         2
  trainable:        True
  input_scaling:    True
  data_reuploading: True
  ansatz:           'he'
  ansatz_layers:    5

training:
  model: 'qkernel'
  batch_size: 10

## Model Training Agen Configuration
agent:
  optimizer:            gd
  lr:                   0.2
  epochs:               500
  train_method:         'random'
  target_accuracy:      0.95
  get_alignment_every:  100
  validate_every_epoch: 1
  base_path:            results/
  lambda_kao:           0.01
  lambda_co:            0.01
  clusters:             4